site:
  about:
    siteName: 'Credera++'

theme:
  primaryColor: '#a3232a'
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'link'
      title: 'Add To Slack'
      url: 'https://slack.com/oauth/authorize?client_id=402674575044.402789997363&scope=channels:history,chat:write:bot,bot'
    - type: 'page'
      itemId: 'API Reference'
    - type: 'page'
      itemId: 'Contact Us'
    - type: 'page'
      itemId: 'Privacy Policy'

    - type: 'separator'
      title: 'About Credera'
    - type: 'link'
      title: 'Learn More'
      url: 'https://www.credera.com/'
    - type: 'link'
      title: 'Contact Us'
      url: 'https://www.credera.com/contact/'

services:
  compilers:
    precompiler:
      customDelimeters:
        - regex: '^/\*---(.*)---\*/'
          group: 1
          parser: 'yml'
          fileExtensions: [ 'js', 'css', 'scss' ]
