site:
  about:
    siteName: 'Crederabot'

theme:
  primaryColor: '#a3232a'
  menu:
    - type: 'page'
      itemId: 'Home'
      title: 'Crederabot Home'
    - type: 'page'
      itemId: 'Privacy Policy'
    - type: 'page'
      itemId: 'API Reference'

    - type: 'separator'
      title: 'Credera++'
    - type: 'page'
      itemId: 'Credera++'
      title: 'Try A Demo'
      anchor: 'interactive-example'
    - type: 'page'
      itemId: 'Credera++'
      title: 'Command Reference'
      anchor: 'command-reference'
    - type: 'link'
      title: 'Add To Slack'
      url: 'https://slack.com/oauth/authorize/?client_id=402674575044.402789997363&scope=channels:history,chat:write:bot,bot'

    - type: 'separator'
      title: 'About Credera'
    - type: 'link'
      title: 'Learn More'
      url: 'https://www.credera.com/'
    - type: 'link'
      title: 'Contact Us'
      url: 'https://www.credera.com/contact/'

allPages:
  components:
    - type: 'pageContent'
      order: 10
    - type: 'template'
      template: 'page-footer'
      order: 100