site:
  about:
    siteName: 'Orchid Netlify Slackbot'

theme:
  primaryColor: '#a3232a'
  menu:
    - type: 'link'
      title: 'Home'
      url: '/'
    - type: 'page'
      itemId: 'Commands'
    - type: 'page'
      itemId: 'API Reference'
    - type: 'link'
      title: 'Add To Slack'
      url: 'https://slack.com/oauth/authorize?client_id=402674575044.402789997363&scope=channels:history,users.profile:read,chat:write:bot,bot,users:read'

allPages:
  layout: single

staticPages:
  layout: single

services:
  compilers:
    precompiler:
      customDelimeters:
        - regex: '^/\*---(.*)---\*/'
          group: 1
          parser: 'yml'
          fileExtensions: [ 'js', 'css', 'scss' ]